config/routes.rb
# == Route Map == [annotate --routes]
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        posts#index
#                     login GET    /login(.:format)                                                                         user_sessions#new
#                           POST   /login(.:format)                                                                         user_sessions#create
#                    logout DELETE /logout(.:format)                                                                        user_sessions#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#              search_posts GET    /posts/search(.:format)                                                                  posts#search
#             post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                           POST   /posts/:post_id/comments(.:format)                                                       comments#create
#          new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                     likes POST   /likes(.:format)                                                                         likes#create
#                      like DELETE /likes/:id(.:format)                                                                     likes#destroy
#             relationships POST   /relationships(.:format)                                                                 relationships#create
#              relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#             read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#       edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#            mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                           PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#         mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # Sidekiqのダッシュボード導入のため
  require 'sidekiq/web'
  if Rails.env.development?
    # 開発環境用letter_opener、 localhost:3000/letter_openerにアクセスしてメールを確認
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    # localhost:3000/sidekiqでsidekiqダッシュボード表示
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root 'posts#index'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  # ユーザー登録フォーム、ユーザー追加アクションのルーティング
  resources :users, only: %i[index new create show]
  # リソース = postsテーブルにとっての１投稿
  # resources = 基本となる7つのアクションをリクエストするルーティングを設定
  # shallow = リソースの関係性を一意に特定できる際に、不必要なURLを短くできるRailsの
  # ルーティングのオプション
  # edit,show,update,destroyでは /posts/post_id/ を省略する
  # https://kossy-web-engineer.hatenablog.com/entry/2018/10/17/063136
  resources :posts, shallow: true do
    # ネスト = ある記述の中に入れ子構造で別の記述をする方法
    # collection = ルーティングにコレクション（/photos/searchのようにidを伴わないパス）を追加するときに使う。
    collection do
      get :search
    end
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    # on: 名前付きルートを指定
    patch :read, on: :member
  end

  # namespace = URLを指定のPATHにしたくて、ファイル構成も指定のものにしたい時
  # scopeではないのは、この後の課題で違うaccounts_controllerがでてくるから？
  # https://qiita.com/ryosuketter/items/9240d8c2561b5989f049
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#  index_comments_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  # defaultでbelongs_toの第一引数に、そのモデルに紐づくモデル名を全て小文字で単数系で設定
  belongs_to :user
  belongs_to :post

  # has_one = その宣言が行われているモデルのインスタンスが、
  #           他方のモデルのインスタンスを「まるごと含んでいる」または「所有している」ことを示す。
  # as: = ポリモーフィック関連を定義
  # activity.rb の belongs_to :subject, polymorphic: true と セットで設定する
  has_many :activity, as: :subject, dependent: :destroy

  validates :body, presence: true, length: { maximum: 1000 }

  # modelに紐付くインスタンスがcreateされた直後に必ず、発火する
  after_create_commit :create_activities

  private

  def create_activities
    # subject: self にあたるモデルによって保存されるsubject_type、subject_idが変わる
    Activity.create(subject: self, user: post.user, action_type: :commented_to_own_post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # remote: true なので html.erb ではなく js.erb が
  # このコントローラのアクションに伴ってレンダリング(対応したjsファイルが出力)される
  # 対応したjsファイルでも設定したインスタンス変数(@comment)を参照できる
  def create
    # ちゃんと user_id, body, post_id 指定して、コメントをインスタンス変数に代入できている
    @comment = current_user.comments.build(comment_params)
    # コメントの通知メールを送る
    # with() = メイラーアクションへ渡すキーの値を設定
    # メイラーアクション = UserMailer内のメソッド
    # deliver_later = Active Jobと連携して非同期にメール送信を行えるメソッド
    UserMailer.with(user_from: current_user, user_to: @comment.post.user, comment: @comment).comment_post.deliver_later if @comment.save
  end

  def edit
    # _comment.html.slimから
    # params[:id]にはコメントのidが入る
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])
    @comment.update(comment_update_params)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    # .merge = 投稿のページの post.id を引っ張ってきてパラメータに追加
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end

  def comment_update_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.slim
/ 投稿へのコメント部分表示
div id="comment-#{comment.id}"
  .row.no-gutters
    .col-2
      = image_tag comment.user.avatar.url, size: '40x40', class: 'rounded-circle'
    .col-9
      span.font-weight-bold.pr-1
        = comment.user.username
      = comment.body
    .col-1
      - if current_user&.own?(comment)
        / remote: true = js形式でリクエスト、コントローラのアクションを実行した後
        / jsファイル(View)を出力、ページの一部分だけを更新
        / htmlファイルをレンダリングしないのでページ遷移を行わない(非同期)
        / html形式とjs形式でのリクエストの違い参考URL
        / https://qiita.com/__tambo__/items/45211df065e0c037d032

        = link_to comment_path(comment), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'}, remote: true do
          = icon 'far', 'trash-alt', class: 'fa-sm'
        = link_to edit_comment_path(comment), remote: true do
          = icon 'far', 'edit', class: 'fa-sm'
  hr

app/views/comments/_comments.html.slim
/ postsのshow.html.slim内で呼び出される
.comments-box
  / @commentsのデータで_comment.html.slimが書き出される
  = render comments

app/views/comments/_form.html.slim
/ postsの show.html.slim, _modal_form.html.slim内で呼び出されるコメント投稿フォーム
/ remote: true = js形式でリクエスト、コントローラのアクションを実行した後
/ jsファイル(View)を出力、ページの一部分だけを更新
/ htmlファイルをレンダリングしないのでページ遷移を行わない(非同期)
/ html形式とjs形式でのリクエストの違い参考URL
/ https://qiita.com/__tambo__/items/45211df065e0c037d032
/ 新規コメント投稿とコメント編集の両方で同じこのフォームを使う
/ コメント編集時、編集するコメントだけわかればいいのでpostはnil

= form_with model: [post, comment], class: 'd-flex mb-0 flex-nowrap justify-content-between', remote: true do |f|
  = f.text_field :body, class: 'form-control input-comment-body', placeholder: 'コメント'
  = f.submit '投稿', class: 'btn btn-primary btn-raised'

app/views/comments/_modal_form.html.slim
/ モーダルのコメント新規投稿フォーム
.modal#comment-edit-modal
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title コメント編集
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body
        = render 'form', post: nil, comment: comment

app/views/comments/create.js.slim
/ エラーメッセージが空ではないなら
- if @comment.errors.present?
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  / .comments-box(_comments.html.slim)内を_comment.html.slimの内容に置き換える
  / Ajaxなので以前のコメントを残した上でその一番上に新しいコメントを表示
  /.prepend = 先頭にHTMLを挿入する
  / j = escape_javascriptのエイリアス
  | $('.comments-box').prepend("#{j render('comments/comment', comment: @comment)}");
  / フォームに入力していたコメント文を消去
  | $('.input-comment-body').val('');

app/views/comments/destroy.js.slim
/ _comment.html.slim内、divタグの id="comment-#{comment.id}"を指定して、コメントを削除
| $('#comment-#{@comment.id}').remove()

app/views/comments/edit.js.slim
/ モーダルを表示する前に_modal_form.html.slimに変更前のコメントを追加している
/ .html = htmlを変更
/ escape_javascript = javascript用に実行結果(コメント内容)にエスケープ処理をする
| $("#modal-container").html("#{escape_javascript(render 'modal_form', comment: @comment)}");
/ モーダルのコメント投稿フォームを表示(_modal_form.html.slim内のidを指定している)
| $("#comment-edit-modal").modal('show');

app/views/comments/update.js.slim
/ エラーメッセージが空ではないなら
- if @comment.errors.present?
  / アラートでエラーメッセージ表示
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  / _comment.html.slim内、divタグの id="comment-#{comment.id}"を指定してその中で、
  / アクションから渡された新規のコメントを書き出す
  / .html = htmlを変更
  / j = escape_javascriptのエイリアス
  | $("#comment-#{@comment.id}").html("#{j render('comments/comment', comment: @comment)}");
  / モーダルを閉じる
  | $("#comment-edit-modal").modal('hide');