config/routes.rb
# == Route Map == [annotate --routes]
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        posts#index
#                     login GET    /login(.:format)                                                                         user_sessions#new
#                           POST   /login(.:format)                                                                         user_sessions#create
#                    logout DELETE /logout(.:format)                                                                        user_sessions#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#              search_posts GET    /posts/search(.:format)                                                                  posts#search
#             post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                           POST   /posts/:post_id/comments(.:format)                                                       comments#create
#          new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                     likes POST   /likes(.:format)                                                                         likes#create
#                      like DELETE /likes/:id(.:format)                                                                     likes#destroy
#             relationships POST   /relationships(.:format)                                                                 relationships#create
#              relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#             read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#       edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#            mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                           PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#         mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # Sidekiqのダッシュボード導入のため
  require 'sidekiq/web'
  if Rails.env.development?
    # 開発環境用letter_opener、 localhost:3000/letter_openerにアクセスしてメールを確認
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    # localhost:3000/sidekiqでsidekiqダッシュボード表示
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root 'posts#index'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  # ユーザー登録フォーム、ユーザー追加アクションのルーティング
  resources :users, only: %i[index new create show]
  # リソース = postsテーブルにとっての１投稿
  # resources = 基本となる7つのアクションをリクエストするルーティングを設定
  # shallow = リソースの関係性を一意に特定できる際に、不必要なURLを短くできるRailsの
  # ルーティングのオプション
  # edit,show,update,destroyでは /posts/post_id/ を省略する
  # https://kossy-web-engineer.hatenablog.com/entry/2018/10/17/063136
  resources :posts, shallow: true do
    # ネスト = ある記述の中に入れ子構造で別の記述をする方法
    # collection = ルーティングにコレクション（/photos/searchのようにidを伴わないパス）を追加するときに使う。
    collection do
      get :search
    end
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    # on: 名前付きルートを指定
    patch :read, on: :member
  end

  # namespace = URLを指定のPATHにしたくて、ファイル構成も指定のものにしたい時
  # scopeではないのは、この後の課題で違うaccounts_controllerがでてくるから？
  # https://qiita.com/ryosuketter/items/9240d8c2561b5989f049
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  avatar           :string(255)
#  crypted_password :string(255)
#  email            :string(255)      not null
#  salt             :string(255)
#  username         :string(255)      not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_users_on_email     (email) UNIQUE
#  index_users_on_username  (username) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader
  # バリデーションは、正しいデータだけをデータベースに保存するために行われる
  # usernameが重複していないか、空じゃないか
  validates :username, uniqueness: true, presence: true
  # パスワードは３文字以上で objectがdatabaseに保存されていないとき(new_record?)かつ パスワードが更新された時(changes)
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  # パスワードが確認用パスワードと一致しいるかどうか
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  # 確認用パスワードが空じゃないか
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  # e-mailが重複していないか、空じゃないか
  validates :email, uniqueness: true, presence: true

  # has_manyの第一引数に、そのモデルに紐づくモデル名を全て小文字で複数系で設定
  # ユーザーが削除されたときに、そのユーザーに紐付いた(そのユーザーが投稿した)投稿も一緒に削除
  has_many :posts, dependent: :destroy
  # User.find(2).commentsで、ユーザーの所有するコメントを取得できる。
  has_many :comments, dependent: :destroy
  # has_many　:like_postsより上に記述すること
  has_many :likes, dependent: :destroy
  # @user.like_postsとするとuserがlikeしたpostを取得できる
  # likeモデルのuser.idとpost.idの組み合わせを見てUserモデルをLikeモデルを経由してPostモデルと関連づける
  has_many :like_posts, through: :likes, source: :post

  # user対user（多対多）の関係性をアソシエーションで表現していく
  # user.followingをできるように、active_relationshipsを設定する。
  # 外部キーをfollower_idとして指定し、Relationshipモデルを取得する。
  # foreign_key = 外部キーをモデル名_id以外のカラムに指定したい場合,使用
  # class_name = 一つのモデルに対して、二つのアソシエーション経路を組む場合に使用
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  # user.followersをできるように、passive_relationshipsを設定する。
  # 外部キーをfollowed_idとして指定し、Relationshipモデルを取得する。
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy

  # userモデルのだれかから、最終的にfollow関係にあるuserモデルのだれかを参照する
  # source = 関連先テーブル名とアソシエーション名が異なる場合は、sourceオプションを使う
  # user.followingでfollower_idと対になるfollowed_idからそのuser'が'followをしているuserを全て取得する
  has_many :following, through: :active_relationships, source: :followed
  # user.followersでfollowed_idと対になるfollower_idからそのuser'を'followをしているuserを全て取得する
  has_many :followers, through: :passive_relationships, source: :follower

  # ログインしているユーザーへの通知を取ってくるため、関連づけ
  # （_header_activities.html.slim、 mypage/activities_controller内）
  has_many :activities, dependent: :destroy

  # モデルのscope = 複数のクエリをまとめたメソッド
  # DBから新しい順にレコードをcountの数取り出す
  scope :recent, ->(count) { order(created_at: :desc).limit(count) }

  # クラスメソッド = クラスオブジェクトから呼び出すためのメソッド
  # インスタンスメソッド = インスタンスオブジェクトから呼び出すためのメソッド(own?)
  # ログインしている人の投稿だったらtrueを返す
  # current_user.idと投稿のuser_idを判定している
  def own?(object)
    # id = self.id
    id == object.user_id
  end

  def like(post)
    # << = has_manyを設定しているモデル(ここではPost)と新しく関連付けをする（has_manyを
    # 設定すると使えるようになるメソッド）
    # like_posts = self.like_posts
    # current_user.like_postsで得られる投稿(ログインユーザーがいいねした投稿)に、今いいねした投稿を追加。このときlikeテーブルに新しくレコードが作られる。
    like_posts << post
  end

  def unlike(post)
    # delete = has_manyを設定すると使えるようになるメソッド
    like_posts.delete(post)
  end

  def like?(post)
    # like_postsの中にpostオブジェクトが含まれていればtrueを返す。
    like_posts.include?(post)
  end

  # 新しいfolllowしている人(followed_id)、followされている人(follower_id)の組み合わせをrelationshipモデルに追加
  def follow(other_user)
    following << other_user
  end

  # アンフォローしたユーザーとされたユーザーを紐づけていたrelasionshipモデルのレコードを削除
  def unfollow(other_user)
    following.destroy(other_user)
  end

  # current_userがフォローしているユーザーの中にother_userが含まれていればtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # current_userがfollowしているuser.id、current_user自身の投稿をuser.idから投稿を取得
  # self.following_ids << self.id → current_userがfollowしているuserのidの配列に自身のuser.idを追加する
  def feed
    Post.where(user_id: following_ids << id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save # ユーザー登録できた場合
      auto_login(@user)
      redirect_to root_path, success: 'ユーザーを作成しました' # ルート画面に戻る
    else
      flash.now[:danger] = 'ユーザーに作成に失敗しました'
      render :new # ユーザー登録画面へ戻る
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/views/users/_follow.html.slim
/ ログインしているuserがfolllowしているuserのidをクエリ形式のパラメータで渡す
= link_to relationships_path(followed_id: user.id), class: 'btn btn-raised btn-outline-warning', method: :post, remote: true do
  | フォロー

app/views/users/_follow_area.html.slim
/ ログインしていて、表示しているユーザーが自分じゃない場合
/ follow,unfollowボタン表示
- if logged_in? && current_user.id != user.id
  div id="follow-area-#{user.id}"
    - if current_user.following?(user)
      = render 'users/unfollow', user: user
    - else
      = render 'users/follow', user: user

app/views/users/_form.html.erb
<%= form_with url: user_sessions_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/users/_unfollow.html.slim
/ × ログインユーザーのfollower_idと対になるfollowed_idを渡す
/ ○ ログインユーザーのfollower_idと紐づいているuser.id(followed_id)の組み合わせのRelationshipモデルのレコードを取得。パラメータとして送る。(localhost:3000/relationships/12)
= link_to relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), class: 'btn btn-warning btn-raised', method: :delete, remote: true do
  | アンフォロー

app/views/users/_user.html.slim
/ ユーザー一覧ページでユーザーを1人分表示
.user.mb-3.d-flex.justify-content-between
  = link_to user_path(user) do
    = image_tag user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
    = user.username
  = render 'users/follow_area', user: user
hr

app/views/users/index.html.slim
/ ユーザー一覧ページ
.container
  .row
    .col-md-6.col-12.offset-md-3.mb-3
      .card
        .card-body
          / _user.html.slimをレンダリング
          / render partial: 'user', collection: @users
          = render @users
    .col-md-6.col-12.offset-md-3
      = paginate @users

app/views/users/new.html.slim
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true do |f|
        = render 'shared/error_messages', object: @user
        .form-group
          = f.label :username, class: 'bmd-label-floating'
          = f.text_field :username, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'

        = f.submit '登録', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちですか？
        = link_to 'ログインする', login_path

app/views/users/show.html.slim
/ ユーザー詳細ページ
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          / &をつけないと、ログインしていない時、undefined method `id' for nil:NilClass となる
          / ↑ &(ぼっち演算子)がcurrent_userがnullかどうか確かめて、nullの場合.idメソッドを呼び出さず
          /   nillを返しif文の中身を実行しない
          - if current_user&.id == @user.id
            .text-center.mb-3
              = link_to 'プロフィール編集', edit_mypage_account_path, class: 'btn btn-raised btn-warning'
          .text-center.mb-3
            = image_tag @user.avatar.url, size: '100x100', class: 'rounded-circle mr-1'
          .profile.text-center.mb-3
            = @user.username
          .text-center
            = render 'follow_area', user: @user
          hr
          .row
            / partial = viewの一部を別ファイルに切り出し、可読性と再利用性を上げる。
            / Viewでの繰り返し部分を、eachメソッドを使用するのではなく、コレクションをレンダリングすることで実装する。
            = render partial: 'posts/thumbnail_post', collection: @user.posts