config/routes.rb
# == Route Map == [annotate --routes]
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        posts#index
#                     login GET    /login(.:format)                                                                         user_sessions#new
#                           POST   /login(.:format)                                                                         user_sessions#create
#                    logout DELETE /logout(.:format)                                                                        user_sessions#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#              search_posts GET    /posts/search(.:format)                                                                  posts#search
#             post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                           POST   /posts/:post_id/comments(.:format)                                                       comments#create
#          new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                     likes POST   /likes(.:format)                                                                         likes#create
#                      like DELETE /likes/:id(.:format)                                                                     likes#destroy
#             relationships POST   /relationships(.:format)                                                                 relationships#create
#              relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#             read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#       edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#            mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                           PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#         mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # Sidekiqのダッシュボード導入のため
  require 'sidekiq/web'
  if Rails.env.development?
    # 開発環境用letter_opener、 localhost:3000/letter_openerにアクセスしてメールを確認
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    # localhost:3000/sidekiqでsidekiqダッシュボード表示
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root 'posts#index'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  # ユーザー登録フォーム、ユーザー追加アクションのルーティング
  resources :users, only: %i[index new create show]
  # リソース = postsテーブルにとっての１投稿
  # resources = 基本となる7つのアクションをリクエストするルーティングを設定
  # shallow = リソースの関係性を一意に特定できる際に、不必要なURLを短くできるRailsの
  # ルーティングのオプション
  # edit,show,update,destroyでは /posts/post_id/ を省略する
  # https://kossy-web-engineer.hatenablog.com/entry/2018/10/17/063136
  resources :posts, shallow: true do
    # ネスト = ある記述の中に入れ子構造で別の記述をする方法
    # collection = ルーティングにコレクション（/photos/searchのようにidを伴わないパス）を追加するときに使う。
    collection do
      get :search
    end
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    # on: 名前付きルートを指定
    patch :read, on: :member
  end

  # namespace = URLを指定のPATHにしたくて、ファイル構成も指定のものにしたい時
  # scopeではないのは、この後の課題で違うaccounts_controllerがでてくるから？
  # https://qiita.com/ryosuketter/items/9240d8c2561b5989f049
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
  end
end

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  navbarTogglerDemo02.collapse.navbar-collapse
    form.form-inline.my-2.my-lg-0.mr-auto
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'ポスト一覧', 'posts_path', class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_commented_to_own_post.html.slim
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  object
    = link_to '投稿', post_path(activity.subject.post)
  | に
  object
    = link_to 'コメント', post_path(activity.subject.post, anchor: "comment-#{activity.subject.id}")
  | しました
  .ml-auto
    = l activity.created_at, format: :short

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_followed_me.html.slim
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  = image_tag activity.subject.follower.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.follower.username, user_path(activity.subject.follower)
  | があなたをフォローしました
  .ml-auto
    = l activity.created_at, format: :short

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to new_post_path, class: 'nav-link' do
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        .dropdown
          a#dropdownMenuButton.nav-link.position-relative href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
            = icon 'far', 'heart', class: 'fa-lg'
            /未読の数をハートアイコンの上に表示
            = render 'shared/unread_badge'
          #header-activities.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
            /ヘッダーの通知ボタンをクリック時
            = render 'shared/header_activities'

      li.nav-item
        = link_to user_path(current_user), class: 'nav-link' do
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_activities.html.slim
/ヘッダーの通知ボタンをクリック時の処理
- if current_user.activities.present?
  - current_user.activities.recent(10).each do |activity|
    = render "shared/#{activity.action_type}", activity: activity
  - if current_user.activities.count > 10
    = link_to 'すべてみる', mypage_activities_path, class: 'dropdown-item justify-content-center'
- else
  .dropdown-item
    | お知らせはありません

app/views/shared/_like_to_own_post.html.slim
.dropdown-item
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  = link_to '投稿', post_path(activity.subject.post)
  | にいいねしました
  .ml-auto
    = l activity.created_at, format: :short
.dropdown-divider

app/views/shared/_liked_to_own_post.html.slim
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  object
    = link_to '投稿', post_path(activity.subject.post)
  | にいいねしました
  .ml-auto
    = l activity.created_at, format: :short

app/views/shared/_modal.html.slim
#modal-container

app/views/shared/_unread_badge.html.slim
/ 未読の数をハートアイコンの上に表示
- if current_user.activities.unread.count > 0
  / top: 0; right:0 で右上に寄せて表示
  span.badge.badge-warning.navbar-badge.position-absolute style='top: 0; right:0;'
    = current_user.activities.unread.count