config/routes.rb
# == Route Map == [annotate --routes]
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        posts#index
#                     login GET    /login(.:format)                                                                         user_sessions#new
#                           POST   /login(.:format)                                                                         user_sessions#create
#                    logout DELETE /logout(.:format)                                                                        user_sessions#destroy
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user GET    /users/:id(.:format)                                                                     users#show
#              search_posts GET    /posts/search(.:format)                                                                  posts#search
#             post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                           POST   /posts/:post_id/comments(.:format)                                                       comments#create
#          new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#              edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                   comment GET    /comments/:id(.:format)                                                                  comments#show
#                           PATCH  /comments/:id(.:format)                                                                  comments#update
#                           PUT    /comments/:id(.:format)                                                                  comments#update
#                           DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                     likes POST   /likes(.:format)                                                                         likes#create
#                      like DELETE /likes/:id(.:format)                                                                     likes#destroy
#             relationships POST   /relationships(.:format)                                                                 relationships#create
#              relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#             read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#       edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#            mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                           PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#         mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # Sidekiqのダッシュボード導入のため
  require 'sidekiq/web'
  if Rails.env.development?
    # 開発環境用letter_opener、 localhost:3000/letter_openerにアクセスしてメールを確認
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    # localhost:3000/sidekiqでsidekiqダッシュボード表示
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root 'posts#index'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'

  # ユーザー登録フォーム、ユーザー追加アクションのルーティング
  resources :users, only: %i[index new create show]
  # リソース = postsテーブルにとっての１投稿
  # resources = 基本となる7つのアクションをリクエストするルーティングを設定
  # shallow = リソースの関係性を一意に特定できる際に、不必要なURLを短くできるRailsの
  # ルーティングのオプション
  # edit,show,update,destroyでは /posts/post_id/ を省略する
  # https://kossy-web-engineer.hatenablog.com/entry/2018/10/17/063136
  resources :posts, shallow: true do
    # ネスト = ある記述の中に入れ子構造で別の記述をする方法
    # collection = ルーティングにコレクション（/photos/searchのようにidを伴わないパス）を追加するときに使う。
    collection do
      get :search
    end
    resources :comments
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: [] do
    # on: 名前付きルートを指定
    patch :read, on: :member
  end

  # namespace = URLを指定のPATHにしたくて、ファイル構成も指定のものにしたい時
  # scopeではないのは、この後の課題で違うaccounts_controllerがでてくるから？
  # https://qiita.com/ryosuketter/items/9240d8c2561b5989f049
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  images     :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  # belongs = 属する
  belongs_to :user
  # PostモデルにCarrierwaveを関連付け
  mount_uploaders :images, PostImageUploader
  # MySQL5.7からならカラムを作る時点でJASON型にすればいい
  # 配列で送られてきた画像データをDBにはただの一つの文字列(string型)として保存
  # 画像をDBから取り出すときその文字列を配列だと認識させるためにserialize,JASONを使う
  serialize :images, JSON
  # 投稿が削除されたときに、その投稿に紐付いたコメントも一緒に削除,
  # ここに belongs_to :user, dependent: :destroyをつけると投稿が削除されたときにユーザーも削除されてしまう
  # Post.find(20).commentsで、投稿に対するコメントを取得できる。
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  # @post.like_usersとするとpostにlikeしているuserを取得できる
  # PostモデルをLikeモデルを経由してUserモデルと関連づける
  has_many :like_users, through: :likes, source: :user

  # has_one = その宣言が行われているモデルのインスタンスが、
  #           他方のモデルのインスタンスを「まるごと含んでいる」または「所有している」ことを示す。
  # as: = ポリモーフィック関連を定義
  has_many :activity, as: :subject, dependent: :destroy
  # 投稿した文章が空じゃないか
  validates :body, presence: true, length: { maximum: 1000 }
  # 投稿した画像が空じゃないか
  validates :images, presence: true
  # wordが含まれる投稿を取得
  # -> = lambda(変数に代入できる関数をその場で生成する構文の略記法)
  # ? = プレースホルダ(クエリに変数を書ける、SQLインジェクション対策になる)
  # https://railsguides.jp/security.html#sqlインジェクション
  scope :body_contain, ->(word) { where('body LIKE ?', "%#{word}%") }
  # postテーブルをベースにcommentsテーブルを結合
  scope :comment_body_contain, ->(word) { joins(:comments).where('comments.body LIKE ?', "%#{word}%") }
  scope :username_contain, ->(word) { joins(:users).where('username LIKE ?', "%#{word}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create edit update destroy]
  # GETアクション
  def edit
    @post = current_user.posts.find(params[:id])
  end

  def index
    # 投稿データを作成された時間で降順に並べ直して代入
    # postテーブルのuser_idとuserテーブルのidを対応させる方法で二つのテーブルを左外部結合する
    # https://qiita.com/naoki_mochizuki/items/3fda1ad6594c11d7b43c
    # N＋1問題を解決するためにincludesを使いUserとPostをまとめて、一回ずつloadするだけにしている
    # ページネーションをつけたいデータに.page(params[:page])を追加
    # params[:page] 指定されたページ番号が入る
    @posts = if current_user
               # ログインしている場合、自分とフォローしているuserの投稿のみ表示
               current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
             else
               # ログインしていない場合、すべてのuserの投稿を表示
               Post.all.includes(:user).page(params[:page]).order(created_at: :desc)
             end

    # User.order(created_at: :desc).limit(5)
    @users = User.recent(5)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    # 上から新しいコメントを表示するために order(created_at: :desc)
    # N+1問題解消のためincludes(:user)
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @comment = Comment.new
  end

  # POSTアクション
  def create
    # ここで画像がリサイズされる
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def update
    # find_by = 検索したい条件に合うレコードから最初に一致した１件だけを拾ってくる
    # find = 主キー(ID)を使用して、特定のオブジェクトを検索する
    # IDがわかっている場合は、findメソッド
    # IDが不明で、別の条件でレコード検索をしたい場合は、find_byメソッド
    @post = current_user.posts.find(params[:id])
    # update_atributes updateの別名のメソッド
    if @post.update(post_params)
      redirect_to posts_path success: '投稿を更新しました' # show.html.slimへ
    else
      flash.now[:danger] = '投稿の更新に失敗しました'
      # redirect_to,render = コントローラーを経由するか、そのままビューを表示するか
      # redirectではなくrender もう@post内にすでに投稿内容が入っているから
      # :edit ビューを指定
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    # destroy! = 削除できなかったときエラーが表示される(flashではなく)
    @post.destroy!
    redirect_to root_path, success: '投稿を削除しました'
  end

  # メソッド実行前にset_search_posts_formメソッド実行
  # キーワードで検索してsearch.html.slimをレンダリング
  def search
    @posts = @search_form.search.includes(:user).page(params[:page])
  end

  private

  def post_params # ストロングパラメータ = Web上から入力されてきた値を制限することで、
    # 不正なパラメータを防ぐ仕組み DBに受け取る値を制限
    params.require(:post).permit(:body, images: []) # requireメソッドでPOSTで受け取る値のキー設定
    # permitメソッドで許可して受け取る値を制限
    # 複数のデータを送るときには[]を付けないといけない(DBに入る前までは配列でデータが送られてくるから)
  end
end

app/views/posts/_form.html.slim
/new.html.slim、edit.html.slim内で呼び出される
/local: true = AjaxではなくHTMLとしてフォームを送信
= form_with model: post, local: true do |f|
  = render 'shared/error_messages', object: post
  .form-group
    = f.label :images
    /multiple: true = 画像を複数一度に投稿
    = f.file_field :images, multiple: true, class: 'form-control'
    - post.images.each do |image|
      /アップロードする画像表示
      = image_tag image.url, size: '100x100', class: 'image-thumbnail'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  = f.submit class: 'btn btn-primary btn-raised'

app/views/posts/_like.html.slim
= link_to likes_path(post_id: post.id), method: :post, remote: true do
  = icon 'far', 'heart', class: 'fa-lg'

app/views/posts/_like_area.html.slim
div id="like_area-#{post.id}"
  - if current_user.like?(post)
    / いいねしていた場合
    = render 'unlike', post: post
  - else
    / いいねしていなかった場合
    = render 'like', post: post

app/views/posts/_post.html.slim
/ index.html.slim内で呼び出される。
/ 投稿を一件表示
.card.mb-5.post
  .card-header
    .d-flex.align-items-center
      / ユーザー詳細ページへのリンク
      = link_to user_path(post.user) do
        = image_tag post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = post.user.username
      / 自分の投稿には編集、削除アイコンを表示
      / current_userが nil 出ない時 .own を呼び出し(&&とは違う)
      / 例 foo = 13
      /  　foo&.to_s # => "13"
      - if current_user&.own?(post)
        .ml-auto
          = link_to post_path(post), class: 'mr-3', method: :delete, data: { confirm: '本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) do
            = icon 'far', 'edit', class: 'fa-lg'
      - if current_user && !current_user.own?(post)
        .ml-auto
          = render 'like_area', post: post
  = link_to post_path(post) do
    .swiper-container
      .swiper-wrapper
        - post.images.each do |image|
          .swiper-slide
            = image_tag image.url, class: 'card-img-top'
      .swiper-pagination
  .card-body
    .card-text
      = post.body

app/views/posts/_thumbnail_post.html.slim
/ ☆そのuserの投稿の画像をタイル表示
/ 変数名(thumbnail_post)はパーシャル名と同じにしないといけない
/ class: 'thumbs' = application.scss内に記述
/ post_path(URLヘルパーメソッド) = /posts/:id
/ iconと同じようにimage_tagでリンクに画像を設定
/ thumbnail_post.images.first.url = CarrierWaveがpublic/uploads/post/imagesフォルダから一枚目の画像を持ってくる
/ .col-md-4.mb-3の下の行にコメントを入れると画像が表示されなくなるのは何故なのでしょうか？
.col-md-4.mb-3
  = link_to post_path(thumbnail_post), class: 'thumbs' do
    = image_tag thumbnail_post.images.first.url

app/views/posts/_unlike.html.slim
/ ログインしているユーザーのこの投稿のライクのidを送る
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, remote: true do
  = icon 'fa', 'heart', class: 'fa-lg'

app/views/posts/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-3
      .card
        .card-body
          / _form.html.slim描き出し
          = render 'form', post: @post

app/views/posts/index.html.slim
/ 投稿一覧表示、ユーザー5人分表示
.container
  .row
    .col-md-8.col-12
      - if @posts.present?
        /投稿を全て表示,render partial: 'post', collection: @postsを短縮して書いている
        = render @posts
      - else
        .text-center.font-weight-bold
        | 投稿がありません
      /_post.html.slimには何も書かなくてもkaminariが自動的にページネーションを実装してくれる
      = paginate @posts
    .col-md-4.col-12
      - if logged_in?
        .profile-box.mb-3
          / ログインしているユーザーのアバター、名前表示
          = image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr-1'
          = link_to current_user.username, edit_mypage_account_path
      .users-box
        .card
          .card-header
            | ユーザー
          .card-body
            / ユーザーが5人分ランダムに表示(@users = User.recent(5))
            / render partial: 'user', collection: @users
            = render @users
          .card-footer
            / ユーザー一覧ページへ
            = link_to 'すべて見る', users_path

app/views/posts/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          /_form.html.slim描き出し
          = render 'form', post: @post

app/views/posts/show.html.slim
/ 投稿閲覧画面
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            = image_tag image.url
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.username
        / 自分の投稿には編集、削除アイコンを表示
        - if current_user&.own?(@post)
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post) do
              = icon 'far', 'edit', class: 'fa-lg'
        / ログインしていて、ログインしている人の投稿じゃなかったら
        - if current_user && !current_user.own?(@post)
          .ml-auto
            = render 'like_area', post: @post
    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@post.body)
      hr
      / コメント一覧
      = render 'comments/comments', comments: @comments
    hr.m-0
    .post-comment.p-3
      / showアクションで定義したインスタンス変数を渡す
      = render 'comments/form', post: @post, comment: @comment